import Groq from "groq-sdk";

let groqClient = null;

function getGroqClient() {
  if (!process.env.GROQ_API_KEY) {
    throw new Error("GROQ_API_KEY not loaded");
  }

  if (!groqClient) {
    groqClient = new Groq({
      apiKey: process.env.GROQ_API_KEY,
    });
  }

  return groqClient;
}

export async function analyzeMedicalText(medicalText) {
  const groq = getGroqClient();

  const prompt = `
You are a medical document explainer for general users.

STRICT OUTPUT RULES:
- Output plain text only
- Do NOT use markdown
- Do NOT use bullet points
- Do NOT use symbols like *, -, **
- Use numbered section headings only (1., 2., 3., etc.)
- Each section title must end with a colon
- Separate sections using line breaks
- Do NOT give medical advice

STRUCTURE YOUR RESPONSE EXACTLY LIKE THIS:

1. Document Summary:
Briefly describe what type of medical document this is and what information it contains.

2. Patient Information:
Explain any patient-related details mentioned in the document.

3. Medical Findings:
Explain what is written in the document regarding medicines, tests, or observations.

4. Theoretical Explanation:
Provide general educational information about the medical terms mentioned (for example, what the medicine is commonly used for and what dosage usually refers to). Keep this theoretical and non-advisory.

5. Understanding the Instructions:
Explain in simple language what the instructions in the document mean for a normal person.

6. Limitations of the Document:
Explain what information is missing or not present in this document, if any.

End with this disclaimer exactly:
"This explanation is generated by AI for informational and educational purposes only and is not a medical opinion."

DOCUMENT TO ANALYZE:
${medicalText}
`;


  const completion = await groq.chat.completions.create({
    model: "llama-3.1-8b-instant",
    messages: [{ role: "user", content: prompt }],
    temperature: 0.25,
  });

  return completion.choices[0].message.content.trim();
}
